export enum ApiMethod {
  Get = 'get',
  Put = 'put',
  Post = 'post',
  Delete = 'delete',
  Patch = 'PATCH',
}

export enum ApiEventStep {
  Request = 'REQUEST',
  Success = 'SUCCESS',
  Failure = 'FAILURE',
}

export enum ApiEventName {
  ActiveReplicas = 'ACTIVE_REPLICAS',
  AnomalyAlerts = 'ANOMALY_ALERTS',
  AnomalySettings = 'ANOMALY_SETTINGS',
  InsightsInfo = 'INSIGHTS_INFO',
  InstrumentationArtifacts = 'INSTRUMENTATION_ARTIFACTS',
  InstrumentationDomains = 'INSTRUMENTATION_DOMAINS',
  EgressDefaults = 'EGRESS_DEFAULTS',
  EgressRules = 'EGRESS_RULES',
  K8sRisks = 'K8S_RISKS',
  K8sAlerts = 'K8S_ALERTS',
  K8sChanges = 'K8S_CHANGES',
  K8sPolicies = 'K8S_POLICIES',
  K8sPolicyCreate = 'K8S_POLICY_CREATE',
  K8sRulesTable = 'K8S_RULES_TABLE',
  K8sRulesTemplates = 'K8S_RULES_TEMPLATES',
  K8sCustomRules = 'K8S_CUSTOM_RULES',
  KafkaActivity = 'KAFKA_ACTIVITY',
  NetworkAlerts = 'NETWORK_ALERTS',
  NetworkActivitySummary = 'NETWORK_ACTIVITY_SUMMARY',
  NetworkBlockedMessages = 'NETWORK_BLOCKED_MESSAGES',
  NetworkAlertsSummary = 'NETWORK_ALERTS_SUMMARY',
  NotificationsSettings = 'NOTIFICATIONS_SETTINGS',
  NetworkRules = 'NETWORK_RULES',
  NetworkRuleRecommendations = 'NETWORK_RULE_RECOMMENDATIONS',
  ReportCards = 'REPORT_CARDS',
  SessionLogin = 'SESSION_LOGIN',
  SessionRenewToken = 'SESSION_RENEW_TOKEN',
  ThreatAlerts = 'THREAT_ALERTS',
  ThreatRules = 'THREAT_RULES',
  ThreatRuleCategories = 'THREAT_CATEGORIES',
  ThreatDetails = 'THREAT_DETAILS',
  ThreatEndpointDetails = 'THREAT_ENDPOINT_DETAILS',
  UsersList = 'USERS_LIST',
  WorkloadZoomActivity = 'WORKLOAD_ZOOM_DETAILS',
  WorkloadZoomAlerts = 'WORKLOAD_ZOOM_ALERTS',
  WorkloadActivityHistory = 'WORKLOAD_ACTIVITY_HISTORY',
}
